#server
server:
  port: 80
  servlet:
    context-path: /

#datasource,mybatis,thymeleaf
spring:
  datasource:
    url: jdbc:mysql:///cfdb?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  task:
    execution:
      pool:
        core-size: 16
        max-size: 1000
        queue-capacity: 2000
        allow-core-thread-timeout: false
        keep-alive: 30
      thread-name-prefix: db-service-thread-
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*/*.xml

#log
logging:
  level:
    com.crossfile.core: debug